### ISSUE TITLE
Генератор тегов

### ISSUE THREAD

**Issue by banbanan** [Japing/Payhide-DLE-Billing#1]
не сохраняется в настройках модуля данные во вкладке Генератор тегов.
не помогло даже добавление кнопки 
`$Content .= $this->Dashboard->ThemePadded( $this->Dashboard->MakeButton("save", $this->Dashboard->lang['save'], "green") );`
в конце строки adm.main.php
подскажи пожалуйста как решить?

**Comment by Japing** [comment]
Никак, там ничего и не должно сохранятся.

**Comment by banbanan** [comment]
благодарю
